language: r
cache: packages

r:
# reenable once oldrel is at least DESCRIPTION's minimum R version
#  - oldrel
  - release
  - devel

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - r: devel

branches:
  only: 
      - master

