language: r
cache: packages

matrix:
  - fast_finish: true
  - allow_failures:
    - r: devel

r:
# reenable once oldrel is at least DESCRIPTION's minimum R version
#  - oldrel
  - release
  - devel

os:
  - linux
  - osx